config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root to: 'application#home'

  resources :products do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :brands, only: [:new, :create, :index]

  resources :products

  resources :reviews do
    resources :comments
  end

    devise_for :users, controllers: {
     sessions: 'users/sessions',
     omniauth_callbacks: 'users/omniauth_callbacks'
   }

   resources :users, only: [:show]

  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product, only: [:new, :create, :edit, :index]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def new
    @review = Review.new
 end

  def index
    @reviews = current_user.reviews
    respond_to do |f|
     f.html
     f.json {render json: @reviews}
 end
  end

def show
   respond_to do |f|
   f.html
   f.json {render json: @review, layout: false}
   # @comments = @review.comments
   # @comment = @review.comments.build
   # f.json {render json: @comment, layout: false}
end
end

 def create
     @review = current_user.reviews.build(review_params)
     @review.product_id = @product.id
       respond_to do |f|
         if @review.save
         f.html { redirect_to @review, notice: 'Review was successfully created.' }
          f.json { render :show, status: :created, location: @review }
      else
         f.html { render :new }
         f.json { render json: @review.errors, status: :unprocessable_entity }
       end
     end
end

  def edit
  end

  def update
      @review.update_attributes(review_params)
    if  @review.save
      redirect_to user_path(current_user.id)
    else
      @review.errors.add(:base, "You must be the original creator to make changes
      to this review.")
      render :edit
    end
  end

  def destroy
    @review.delete
    redirect_to product_reviews_path(@product)
  end


  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_product
    @product = Product.find_by(params[:product_id])
  end

  def review_params
    params.require(:review).permit(:title, :body, :product_id)
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class="title">Write a Review for <%= @product.brand.name %>'s <br><i><%= @product.name %></i></div>
<div class="review_form">

  <%= form_for @review do |f| %>

    <%= f.label :title %>:
    <%= f.text_field :title %><br>

    <%= f.label :body %>:
    <%= f.text_area :body %><br>

    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<%= render 'form' %>

app/views/reviews/index.html.erb
<div class="title"><%= @product.name %> by <%= @product.brand.name %></div>
<% @product.reviews.each do |review| %>
  <div class="review-header">
    <%= review.title %>
  </div>
  <div class="review-content">
    <p><a href="/reviews/<%=review.id%>">"<%= review.body[0...50] %>..."</a> <br>by <i><%= review.user.email %></i></p>
</div>

<% if review.comments.present? %>
<br><a href="/reviews/<%=review.id%>" class="load-comments">Show all comments</a>


<div class="review-<%=review.id%>">
<div class="review-comments-<%=review.id%>">
</div>
</div>

<% else %>

  <a href="/reviews/<%=review.id%>">Add a New Comment</a>
<% end %>
<% end %>

<div class="footer-links">
    <%= link_to "Write a New Review", new_product_review_path(@product.id) %>
</div>
<div class="footer-links">
  <% if Product.last %>
  <%= link_to "Browse More Products", products_path, class: 'all-products' %>
  <% else %>
  <%= link_to "Next Product", product_reviews_path((@product.id)+1)%>
  <% end %>
</div>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<div class="review-container">
  <div class="review-header">
    <div class="title"><%= @review.title %></div>
      written by <%= @review.user.email %>
</div>
  <div class="review-body">
      <p><%= @review.body %></p>
  </div>


  <div class="review-links">
  <%= link_to "Edit Review", edit_review_path(@review.id) %>


  <% if @review.comments.present? %>
  <br><a href="/reviews/<%=@review.id%>" class="load-comments">Show all comments</a>
  <div class="review-comments-<%=@review.id%>">
  </div>

  <% else %>
    <a href="/reviews/<%=review.id%>">Add a New Comment</a>
  <% end %>


      <%= form_for(@review.comments.build, :url => review_comments_path(@review)) do |f|  %>
      <%= f.text_area :content %>

      <p><%= f.submit %></h3></p>
      <% end %>

<% if current_user.id = @review.user_id %>
<%= link_to 'Edit Review', edit_review_path(@review) %>
<% else %>
<% end %> |
<%= link_to 'Back', reviews_path %>
</div>